### ISSUE TITLE
Could not subtitle connect to video player

### ISSUE THREAD

**Issue by Bellacrazy74** [jacklul/USharpVideo-Subtitles#2]
I tried to set up on VRchat world to make a subtitle for the video player. It seems not working right when I tested paste subtitle, and nothing happened. I went to your VRchat world subtitle. Your subtitle is working with video than my VRchat world. Is there a subtitle to connect video player match install?

**Comment by jacklul** [comment]
What exactly is not working:
- You can't paste the text at all
- You can paste the text but it does not load
- You can paste the text, it loads but never shows up on the player screen

**Comment by Bellacrazy74** [comment]
It's "You can paste the text. It loads but never shows up on the play screen" I believe

**Comment by jacklul** [comment]
Have you looked at the installation step #7 note?

**Comment by Bellacrazy74** [comment]
It is worked! Thank you for helping.
