### ISSUE TITLE
My world if possible to add list?

### ISSUE THREAD

**Issue by Bellacrazy74** [jacklul/USharpVideo-Subtitles#3]
My (World) Subtitles CC Theater link is https://vrchat.com/home/launch?worldId=wrld_32de345c-128f-4a5f-9bab-f47cd6469689

If it is possible to add a list? 

I am not done working on it because I am looking for a playlist without a link or subtitle. Just find the trigger box for loading quick player and subtitle. How do I do that? Thank you.

**Comment by jacklul** [comment]
> My (World) Subtitles CC Theater link is https://vrchat.com/home/launch?worldId=wrld_32de345c-128f-4a5f-9bab-f47cd6469689
> 
> If it is possible to add a list?

I would really like to keep only non-wip worlds on that list... for now.

> I am not done working on it because I am looking for a playlist without a link or subtitle. Just find the trigger box for loading quick player and subtitle. How do I do that? Thank you.

You want to create a button that loads a video + subtitles? Example how it's done is in the example scene.
