### ISSUE TITLE
This file is not processed/cleaned up properly

### ISSUE THREAD

**Issue by owlboy** [jacklul/USharpVideo-Subtitles#4]
[problimatic-file.srt.zip](https://github.com/jacklul/USharpVideo-Subtitles/files/12707573/problimatic-file.srt.zip)

Formatting tags are not filtered out and newline `\n` markers do not work.

This is the first time I have run into this issue.

**Comment by jacklul** [comment]
Was it loaded through URL?
It doesn't seem to happen when I paste it.
That file seems to be using \r\n line endings which are also handled, perhaps if it was loaded from the URL the server replied with some weirdness like \n\r.

**Comment by jacklul** [comment]
Would you mind testing this `SubtitleManager.cs` if it works for you: https://github.com/jacklul/USharpVideo-Subtitles/blob/36943cc6aef7a0c7f9bd693032caaed21da1a1de/Assets/USharpVideoSubtitles/Scripts/SubtitleManager.cs

I've tested it in Unity and it seems to be working, I've also tried to give it a complex case like this one:
```
1
00:00:000--> 00:01:00,000
{\an3}<font color="yellow"><i>This is the police{\fscx125\fscy123\fn7th Service Condensed}!{\r}</i></font>
<b>Slow that vehicle down{\fscx125\fscy123\fn7th Service Condensed}!{\r}</b><
```
and it seemed to parse it correctly!

**Comment by owlboy** [comment]
I’ll try to give it a shot soon!

I appreciate you taking the time to look at this issue.

**Comment by jacklul** [comment]
Hey, were you able to test it out?

**Comment by owlboy** [comment]
Hello!

Sorry for the delay. I dropped this into my current up-to-date install of the 1.1.0 release, in a fully up-to-date project using Unity 2022 with VRCSDK v3.5. I tested with the original problem .srt. Everything seems to work as expected!

Thank you! I really appreciate this component. Sorry for failing to get back to you promptly.

**Comment by owlboy** [comment]
Also, if you would like to mention my theater on the readme, you can list "The Vantage - By OwlBoy". I've been running it since 2017. It's a private space, so it can't be linked. It's the one mentioned/shown in my "making a theater" [page](https://thegreatpug.com/vrchat-making-a-theater/).

Reach out in-app if you would like to visit!

**Comment by jacklul** [comment]
Glad it all works.
I keep only public worlds on the list, I don't think there is any advantage of mentioning a world that person reading can't visit easily.
