### ISSUE TITLE
Issue with French Subtitles

### ISSUE THREAD

**Issue by TORCHEBUGNE** [jacklul/USharpVideo-Subtitles#5]
Hi ! Sorry for my english, I've an issue with French Subtitles, when I load it, I ve issue with special characters (é à ç etc...)
Subtitle load it like "?" inside a black square.

Do you know how I can solve this thing ? 

Thank you ! 

B4rTux_

**Comment by jacklul** [comment]
Pretty sure they have to be in UTF-8 format to display correctly
If the world overrides the font then this can also be the cause

**Comment by TORCHEBUGNE** [comment]
Oh sorry I don't see your answer me, thanks you, but I can't do it anymore, I change my world to Unity 2022 and the subtitles doesnt work anymore :'(

**Comment by jacklul** [comment]
Unity change should not break Udon prefabs, thought I haven't looked into upgrading any of my content yet.

Perhaps a failed upgrade procedure?

**Comment by jacklul** [comment]
@TORCHEBUGNE is the error the same as in here https://github.com/jacklul/USharpVideo-Subtitles/issues/6 ?

**Comment by jacklul** [comment]
I am closing this because of no answer
