### ISSUE TITLE
trimStart(Char) variant isn't exposed in Udon sharp anymore

### ISSUE THREAD

**Issue by affectioned** [jacklul/USharpVideo-Subtitles#6]
Assets/USharpVideoSubtitles/Scripts/SubtitleManager.cs(545,75): Method is not exposed to Udon: 'text.Substring(text.IndexOf(@"{\an") + 6).TrimStart(' ')'
![Code_2YAI6q2D54](https://github.com/jacklul/USharpVideo-Subtitles/assets/61197745/7d085219-5ed2-4b6b-9b32-b05daa9d67b8)

this could be fixed by changing to a different trimStart variant, my VRChat SDK - Worlds version is 3.5.0

**Comment by jacklul** [comment]
v1.2.0 beta does not use that method so I would try that instead
I haven't updated to Unity 2022 yet so I'm not up to date with the changes

_Days since VRChat broke something in the SDK: 0_

**Comment by affectioned** [comment]
> v1.2.0 beta does not use that method so I would try that instead I haven't updated to Unity 2022 yet so I'm not up to date with the changes

oh i just use TrimStart(new char[' ']) in the meantime, seems to work exactly like original code

![Code_Bc5o48Fknc](https://github.com/jacklul/USharpVideo-Subtitles/assets/61197745/7d91beab-2d93-4fda-8b30-3bcb2700ccac)

**Comment by jacklul** [comment]
This will be fixed in future release of VRChat: https://feedback.vrchat.com/sdk-bug-reports/p/350-beta1-stringtrim-stringtrimstart-and-stringtrimend-are-not-exposed-to-udon-i

**Comment by jacklul** [comment]
Fixed in VRChat SDK 3.6.0.
