### ISSUE TITLE
Subtitles/SRT files are not being sent to other players + Non-instance owner is unable to enter in field. 

### ISSUE THREAD

**Issue by Garret27** [jacklul/USharpVideo-Subtitles#7]
It seems that people are not being sent the SRT file in the new Unity 2022. The subtitles load up for the instance owner + if they enter the srt in with local enabled. 

It also seems like the non-instance owner is not able to enter in the text box field for the SRT.

**Comment by jacklul** [comment]
Did you encounter the issue mentioned in https://github.com/jacklul/USharpVideo-Subtitles/issues/6 ? Or used the beta version?

**Comment by Garret27** [comment]
I am using the beta. But it doesn't look like I am encountering any compiling errors atm like what that one issue is referencing.

**Comment by jacklul** [comment]
It seems like the synchronization bug appears only in the beta version.
Second beta version will be up soon.

**Comment by jacklul** [comment]
Hey, were you able to check out second beta version?

**Comment by Garret27** [comment]
Oh right. Thanks for the checkup. I got it working on my map =)
